# version: '3.9'

# services:
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"

#   web:
#     build: .
#     command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - postgres
#       - redis
# volumes:
#   postgres_data:


version: '3.9'

services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
